-- Great Theologian_Policies
-- Author: lorna
-- DateCreated: 9/24/2019 9:21:40 PM
--------------------------------------------------------------

INSERT OR IGNORE INTO Modifiers
		('ModifierId',										'ModifierType')
VALUES	('HERMETIC_ORDER_GREAT_THEOLOGIAN_LEY_LINE_FAITH',	'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_RESOURCE_YIELD_CHANGE');

INSERT OR IGNORE INTO GovernorPromotionModifiers
		('GovernorPromotionType',				'ModifierId')
VALUES	('GOVERNOR_PROMOTION_HERMETIC_ORDER_3',	'HERMETIC_ORDER_GREAT_THEOLOGIAN_LEY_LINE_FAITH');

INSERT OR IGNORE INTO ModifierArguments
		('ModifierId',										'Name',						'Type',				'Value')
VALUES	('HERMETIC_ORDER_GREAT_THEOLOGIAN_LEY_LINE_FAITH',	'GreatPersonClassType',		'ARGTYPE_IDENTITY',	'GREAT_PERSON_CLASS_JFD_THEOLOGIAN'),
		('HERMETIC_ORDER_GREAT_THEOLOGIAN_LEY_LINE_FAITH',	'YieldType',				'ARGTYPE_IDENTITY',	'YIELD_FAITH'),
		('HERMETIC_ORDER_GREAT_THEOLOGIAN_LEY_LINE_FAITH',	'ResourceType',				'ARGTYPE_IDENTITY',	'RESOURCE_LEY_LINE'),
		('HERMETIC_ORDER_GREAT_THEOLOGIAN_LEY_LINE_FAITH',	'Amount',					'ARGTYPE_IDENTITY',	'1');